plugin_outlet:
  default: "above-right-sidebar-blocks"
hide_on_mobile:
  default: false
url: 'https://connect-app.efinancethai.com/public-api/incoming-events'
title:
  type: string
  default: "กิจกรรมเร็วๆ นี้"