plugin_outlet:
  default: "above-site-header"
hide_on_mobile:
  default: false
apiKey: 'c159790ac5f92bcff28630e7160b979a455d56989e85cf160613492895a05bfb'
apiUsername: 'system'
url: 'https://connect-app.efinancethai.com/public-api/incoming-events'
subscribe_title:
  type: string
  default: "ไม่พลาดทุกข้อมูลที่ช่วยคุณตัดสินใจในการลงทุน"
  description:
    en: "รายละเอียด Subscribe"
subscribe_button_text:
  type: string
  default: "Subscribe"
  description:
    en: "Button text for subscribe."